# Generated by Django 3.0.2 on 2020-01-07 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_name', models.CharField(max_length=200)),
                ('sub_topic', models.CharField(max_length=200)),
                ('topic_dr', models.BigIntegerField()),
            ],
        ),
    ]
