# Generated by Django 3.0.2 on 2020-01-07 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0002_subject_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject_details',
            name='Teacher_name',
            field=models.CharField(max_length=200),
            preserve_default=False,
        ),
    ]
