# Generated by Django 3.0.2 on 2020-01-09 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0004_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='teacher_email',
            field=models.CharField( max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='teacher_subject',
            field=models.CharField(max_length=200),
            preserve_default=False,
        ),
    ]
