# Generated by Django 3.0.2 on 2020-01-15 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0005_auto_20200109_2307'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject_details',
            name='Date',
            field=models.CharField(max_length=200),
            preserve_default=False,
        ),
    ]
