# Generated by Django 3.0.2 on 2020-01-15 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0006_subject_details_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject_details',
            name='Teacher_name',
        ),
    ]
