# Generated by Django 3.0.2 on 2020-01-15 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0008_teacher_teacher_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student_book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_name', models.CharField(max_length=200)),
                ('teacher_subject', models.CharField(max_length=200)),
                ('teacher_topic', models.CharField(max_length=200)),
                ('starting_date', models.CharField(max_length=200)),
                ('topic_dr', models.BigIntegerField()),
            ],
        ),
    ]
