# Generated by Django 3.0.2 on 2020-01-15 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0009_student_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='user_category',
            field=models.CharField( max_length=200),
            preserve_default=False,
        ),
    ]
