# Generated by Django 3.0.2 on 2020-02-04 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0011_auto_20200204_2030'),
    ]

    """operations = [
        migrations.RemoveField(
            model_name='student_book',
            name='topic_dr',
        ),
    ]"""
