# Generated by Django 3.0.2 on 2020-02-04 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0012_remove_student_book_topic_dr'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_book',
            name='student_name',
            field=models.CharField(max_length=200),
            preserve_default=False,
        ),
    ]
