# Generated by Django 3.0.2 on 2020-02-04 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0013_student_book_student_name'),
    ]

    """operations = [
        migrations.DeleteModel(
            name='Msg_admin',
        ),
    ]"""
