# Generated by Django 3.0.2 on 2020-02-04 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0014_delete_msg_admin'),
    ]

    """operations = [
        migrations.RemoveField(
            model_name='student_book',
            name='topic_dr',
        ),
    ]"""
