# Generated by Django 3.0.2 on 2020-02-04 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0015_remove_student_book_topic_dr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_book',
            name='topic_dr',
        ),
    ]
