# Generated by Django 3.0.2 on 2020-02-04 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0016_remove_student_book_topic_dr'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject_details',
            old_name='topic_dr',
            new_name='topic_dir',
        ),
    ]
