# Generated by Django 3.0.2 on 2020-02-04 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0019_student_book_topic_dr'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student_book',
        ),
    ]
