# Generated by Django 3.0.2 on 2020-02-04 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0021_student_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student_book1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=200)),
                ('teacher_name', models.CharField(max_length=200)),
                ('teacher_subject', models.CharField(max_length=200)),
                ('teacher_topic', models.CharField(max_length=200)),
                ('starting_date', models.CharField(max_length=200)),
            ],
        ),
    ]
