# Generated by Django 3.0.2 on 2020-02-04 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0022_student_book1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student_book1',
            old_name='starting_date',
            new_name='starting_date1',
        ),
        migrations.RenameField(
            model_name='student_book1',
            old_name='student_name',
            new_name='student_name1',
        ),
        migrations.RenameField(
            model_name='student_book1',
            old_name='teacher_name',
            new_name='teacher_name1',
        ),
        migrations.RenameField(
            model_name='student_book1',
            old_name='teacher_subject',
            new_name='teacher_subject1',
        ),
        migrations.RenameField(
            model_name='student_book1',
            old_name='teacher_topic',
            new_name='teacher_topic1',
        ),
    ]
