# Generated by Django 3.0.3 on 2020-03-01 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0024_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='logi',
        ),
        migrations.DeleteModel(
            name='Student_book',
        ),
        migrations.DeleteModel(
            name='Student_book1',
        ),
        migrations.DeleteModel(
            name='Subject_details',
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
        migrations.DeleteModel(
            name='Login',
        ),
        migrations.DeleteModel(
            name='Registration',
        ),
    ]
