# Generated by Django 3.0.3 on 2020-03-03 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0026_about_admin_registration_blogs_certificates_course_chapter_course_chapter_content_enrollment_exam_ex'),
    ]

    operations = [
        migrations.DeleteModel(
            name='About',
        ),
        migrations.RemoveField(
            model_name='admin_registration',
            name='Log_id',
        ),
        migrations.DeleteModel(
            name='Blogs',
        ),
        migrations.DeleteModel(
            name='Certificates',
        ),
        migrations.DeleteModel(
            name='Course_chapter',
        ),
        migrations.DeleteModel(
            name='Course_chapter_content',
        ),
        migrations.DeleteModel(
            name='Enrollment',
        ),
        migrations.DeleteModel(
            name='Exam',
        ),
        migrations.DeleteModel(
            name='Exam_results',
        ),
        migrations.DeleteModel(
            name='Feedback',
        ),
        migrations.DeleteModel(
            name='Learning_progress',
        ),
        migrations.DeleteModel(
            name='Messages',
        ),
        migrations.DeleteModel(
            name='Requests',
        ),
        migrations.RemoveField(
            model_name='student_registration',
            name='Log_id',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='Teacher_id',
        ),
        migrations.RemoveField(
            model_name='teacher_registration',
            name='Log_id',
        ),
        migrations.DeleteModel(
            name='Admin_registration',
        ),
        migrations.DeleteModel(
            name='Login',
        ),
        migrations.DeleteModel(
            name='Student_registration',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
        migrations.DeleteModel(
            name='Teacher_registration',
        ),
    ]
