# Generated by Django 3.0.3 on 2020-03-22 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0029_auto_20200322_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher_registration',
            name='Image',
            field=models.ImageField(upload_to=''),
        ),
    ]
