# Generated by Django 3.0.3 on 2020-03-25 02:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0030_auto_20200322_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='course_chapter',
            name='Sub',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learn.Subject'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course_chapter_content',
            name='Chapt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learn.Course_chapter'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='teacher_registration',
            name='Image',
            field=models.ImageField(upload_to='media'),
        ),
    ]
