# Generated by Django 3.0.3 on 2020-03-25 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0031_auto_20200325_0802'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course_chapter_content',
            old_name='Content_type',
            new_name='Content_name',
        ),
        migrations.AddField(
            model_name='course_chapter',
            name='Num_of_images',
            field=models.IntegerField(),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course_chapter',
            name='Num_of_paragraphs',
            field=models.IntegerField(),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course_chapter_content',
            name='Is_image',
            field=models.BooleanField(),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course_chapter_content',
            name='Is_paragraph',
            field=models.BooleanField(),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course_chapter_content',
            name='Is_video',
            field=models.BooleanField(),
            preserve_default=False,
        ),
    ]
