# Generated by Django 3.0.3 on 2020-03-25 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0032_auto_20200325_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='Teacher_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learn.Login'),
        ),
    ]
