# Generated by Django 3.0.3 on 2020-03-27 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0035_auto_20200327_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='Teacher_response',
            field=models.CharField(max_length=200),
        ),
    ]
