# Generated by Django 3.0.3 on 2020-03-27 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0036_auto_20200327_0903'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exam',
            old_name='Answers',
            new_name='Correct_answer',
        ),
        migrations.RenameField(
            model_name='exam',
            old_name='Questions',
            new_name='Option1',
        ),
        migrations.AddField(
            model_name='exam',
            name='Option2',
            field=models.TextField(),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exam',
            name='Option3',
            field=models.TextField(),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exam',
            name='Question',
            field=models.TextField(),
            preserve_default=False,
        ),
    ]
