# Generated by Django 3.0.3 on 2020-03-27 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0037_auto_20200327_1233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='Teacher_id',
        ),
    ]
