# Generated by Django 3.0.3 on 2020-03-28 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0038_remove_subject_teacher_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment',
            name='Teacher_email',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='Teacher_name',
        ),
    ]
