from django.contrib import admin
from .models import *
admin.site.register(Login)
admin.site.register(Admin_registration)
admin.site.register(Student_registration)
admin.site.register(Teacher_registration)
admin.site.register(Subject)
admin.site.register(Course_chapter)
admin.site.register(Course_chapter_content)
admin.site.register(Enrollment)
admin.site.register(Learning_progress)
admin.site.register(Feedback)
admin.site.register(Messages)
admin.site.register(Certificates)
admin.site.register(Requests)
admin.site.register(Exam)
admin.site.register(Exam_results)
admin.site.register(About)
admin.site.register(Blogs)