from django.urls import path
import learn.views
urlpatterns = [
    path('',learn.views.home,name = 'home'),
    path('adminn/',learn.views.admin_rg,name = 'adminn'),
    path('home/',learn.views.home,name = 'home'),
    path('register_st/',learn.views.register_st,name = 'register_st'),
    path('register_tr/',learn.views.register_tr,name = 'register_tr'),
    path('login/',learn.views.login,name = 'login'),
    path('student_home/', learn.views.student_home, name='student_home'),
    path('update_pr_st/', learn.views.update_pr_st, name='update_pr_st'),
    path('update_pr_tr/', learn.views.update_pr_tr, name='update_pr_tr'),
    path('edit_subject/<id>', learn.views.edit_subject, name='edit_subject'),
    path('delete_subject/<id>', learn.views.delete_subject, name='delete_subject'),
    path('add_subject', learn.views.add_subject, name='add_subject'),
    path('teacher_home', learn.views.teacher_home, name='teacher_home'),
    path('logout', learn.views.logout, name='logout'),
    path('subject_tr', learn.views.subject_tr, name='subject_tr'),
    path('subject_tr1', learn.views.subject_tr1, name='subject_tr1'),
    path('subject_tr1', learn.views.subject_tr1, name='subject_tr1'),
    path('admin_home/',learn.views.admin_home,name = 'admin_home'),
    path('stu_sub_selnew', learn.views.stu_sub_selnew, name='stu_sub_selnew'),
    path('st_sub_selnew2', learn.views.st_sub_selnew2, name='st_sub_selnew2'),
    path('disp_teach', learn.views.disp_teach, name='disp_teach'),
    path('stu_buk_teacher', learn.views.stu_buk_teacher, name='stu_buk_teacher'),
    path('upl_cer', learn.views.upl_cer, name='upl_cer'),
    path('do_cer', learn.views.do_cer, name='do_cer'),
    path('about', learn.views.about, name='about'),
    path('adm_prof', learn.views.admin_prof, name='adm_prof'),
    path('del_admin/<id>', learn.views.del_admin, name='del_admin'),
    path('edit_admin/<id>', learn.views.edit_admin, name='edit_admin'),
    path('bnb', learn.views.bnb, name='bnb'),
    path('chapter_tr', learn.views.chapter_tr, name='chapter_tr'),
    path('edit_chapter/<id>', learn.views.edit_chapter, name='edit_chapter'),
    path('ch_co_tr', learn.views.ch_co_tr, name='ch_co_tr'),
    path('edit_content/<id>', learn.views.edit_content, name='edit_content'),
    path('delete_content/<id>', learn.views.delete_content, name='delete_content'),
    path('add_ch_con', learn.views.add_ch_con, name='add_ch_con'),
    path('sub/', learn.views.sub, name='sub'),
    path('add_chapter', learn.views.add_chapter, name='add_chapter'),
    path('add_chapter1', learn.views.add_chapter1, name='add_chapter1'),
    path('add_chapter_c1', learn.views.add_chapter_c1, name='add_chapter_c1'),
    path('delete_chapter/<id>', learn.views.delete_chapter, name='delete_chapter'),

]